version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: knex
    versions:
    - 0.21.16
    - 0.21.17
    - 0.21.18
    - 0.21.19
    - 0.95.1
    - 0.95.2
    - 0.95.3
  - dependency-name: config
    versions:
    - 3.3.3
    - 3.3.4
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.2.1
